import os, sys, inspect
from dbCommands import *
import cgi
import cgitb; cgitb.enable()

class initializeLanguages():
    
    def __init__:
        AddToDatabaseCommand('Language', ['name', 'creator', 'yearIntroduced', 'operatingSystem', 'versionNumber', 'depFunctions', 'newFunctions', 'allFunctions'], ['JAVA', 'James Gosling', '1995', 'Cross-Platform', '1.0', ['javaFunction1', 'javaFunction2', 'javaFunction3', 'javaFunction4'],['javaFunction11', 'javaFunction12'], ['javaFunction11', 'javaFunction12', 'javaFunction10', 'javaFunction 9'], ['had a single week to develop code']])
        AddToDatabaseCommand('Language', ['name', 'creator', 'yearIntroduced', 'operatingSystem', 'versionNumber', 'depFunctions', 'newFunctions', 'allFunctions'], ['JAVA', 'James Gosling', '1995', 'Cross-Platform', '2.0', ['javaFunction1', 'javaFunction2', 'javaFunction3', 'javaFunction4'],['javaFunction11', 'javaFunction12'], ['javaFunction11', 'javaFunction12', 'javaFunction10', 'javaFunction 9'], ['had a single week to develop code']])
        AddToDatabaseCommand('Language', ['name', 'creator', 'yearIntroduced', 'operatingSystem', 'versionNumber', 'depFunctions', 'newFunctions', 'allFunctions'], ['JAVA', 'James Gosling', '1995', 'Cross-Platform', '3.0', ['javaFunction1', 'javaFunction2', 'javaFunction3', 'javaFunction4'],['javaFunction11', 'javaFunction12'], ['javaFunction11', 'javaFunction12', 'javaFunction10', 'javaFunction 9'], ['had a single week to develop code']])
        
        AddToDatabaseCommand('Language', ['name', 'creator', 'yearIntroduced', 'operatingSystem', 'versionNumber', 'depFunctions', 'newFunctions', 'allFunctions'], ['PHP', 'Rasmus Lerdorf', '1995', 'Cross-Platform', '1.0', ['phpFunction1', 'javaFunction2', 'javaFunction3', 'javaFunction4'],['phpFunction11', 'javaFunction12'], ['phpFunction11', 'javaFunction12', 'javaFunction10', 'javaFunction 9'], ['had a single week to develop code']])
        AddToDatabaseCommand('Language', ['name', 'creator', 'yearIntroduced', 'operatingSystem', 'versionNumber', 'depFunctions', 'newFunctions', 'allFunctions'], ['PHP', 'Rasmus Lerdorf', '1995', 'Cross-Platform', '2.0', ['phpFunction1', 'javaFunction2', 'javaFunction3', 'javaFunction4'],['phpFunction11', 'javaFunction12'], ['phpFunction11', 'javaFunction12', 'javaFunction10', 'javaFunction 9'], ['had a single week to develop code']])
        AddToDatabaseCommand('Language', ['name', 'creator', 'yearIntroduced', 'operatingSystem', 'versionNumber', 'depFunctions', 'newFunctions', 'allFunctions'], ['PHP', 'Rasmus Lerdorf', '1995', 'Cross-Platform', '3.0', ['phpFunction1', 'javaFunction2', 'javaFunction3', 'javaFunction4'],['phpFunction11', 'javaFunction12'], ['phpFunction11', 'javaFunction12', 'javaFunction10', 'javaFunction 9'], ['had a single week to develop code']])
        
        AddToDatabaseCommand('Language', ['name', 'creator', 'yearIntroduced', 'operatingSystem', 'versionNumber', 'depFunctions', 'newFunctions', 'allFunctions'], ['PYTHON', 'Guido van Rossum', '1995', 'Cross-Platform', '1.0', ['pythonFunction1', 'javaFunction2', 'javaFunction3', 'javaFunction4'],['pythonFunction11', 'javaFunction12'], ['pythonFunction11', 'javaFunction12', 'javaFunction10', 'javaFunction 9'], ['had a single week to develop code']])
        AddToDatabaseCommand('Language', ['name', 'creator', 'yearIntroduced', 'operatingSystem', 'versionNumber', 'depFunctions', 'newFunctions', 'allFunctions'], ['PYTHON', 'Guido van Rossum', '1995', 'Cross-Platform', '2.0', ['pythonFunction1', 'javaFunction2', 'javaFunction3', 'javaFunction4'],['pythonFunction11', 'javaFunction12'], ['pythonFunction11', 'javaFunction12', 'javaFunction10', 'javaFunction 9'], ['had a single week to develop code']])
        AddToDatabaseCommand('Language', ['name', 'creator', 'yearIntroduced', 'operatingSystem', 'versionNumber', 'depFunctions', 'newFunctions', 'allFunctions'], ['PYTHON', 'Guido van Rossum', '1995', 'Cross-Platform', '3.0', ['pythonFunction1', 'javaFunction2', 'javaFunction3', 'javaFunction4'],['pythonFunction11', 'javaFunction12'], ['pythonFunction11', 'javaFunction12', 'javaFunction10', 'javaFunction 9'], ['had a single week to develop code']])
